server:
  port: 8085
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: STUDENT-SERVICE
        uri: http://localhost:9090
        predicates:
          - Path=/students/**
      - id: EMPLOYEE-SERVICE
        uri: http://localhost:9091
        predicates:
          - Path=/employees/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
